package com.ondrejhrusovsky.teamcity.unrealPlugin.UBT;

import com.ondrejhrusovsky.teamcity.unrealPlugin.ArgBase_String;

import java.util.Map;

public class Arg_Manifest extends ArgBase_String {
    public Arg_Manifest() {
        allowPickFromVCS = true;
        friendlyName = "Manifest Path";
        description = "If set, XML file which lists all output files generated by this UBT task will be created.";
        defaultValue = "Engine\\Intermediate\\Build\\Manifest.xml";
    }

    @Override
    public String makeArgumentString(Map<String, String> params) {
        return IfArgIsPresent(params, "-manifest=" + params.get(toString()));
    }
}
